server:
  port: 8085
#  servlet:
#    context-path: /saas

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_starter?currentSchema=saas_starter
    username: postgres
    password: postgres


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    root: INFO
#    com.saas: DEBUG
#    org.springframework.security: DEBUG