version: v1.0.0

server:
  port: 8085
  servlet:
    context-path: /saas
  forward-headers-strategy: framework
  max-http-request-header-size: 2048KB

management:
  server:
    port: 9888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_starter?currentSchema=saas_starter
    username: postgres
    password: postgres
  jpa:
    generate-ddl: off
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# JWT configuration
jwt:
  secret: ${JWT_SECRET:change-me-dev-secret-32bytes-min}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600}

# Stripe configuration
stripe:
  api-key: ${STRIPE_API_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

#log configuration
logging:
  level:
    root: INFO
    com.saas: DEBUG
    org.springframework.security: DEBUG